### ISSUE TITLE
createPeerAdminCard.sh keeps failing at line 74

### ISSUE THREAD

**Issue by greg2git** [hyperledger/composer-tools#140]
with this message: "No version of composer-cli has been detected, you need to install composer-cli at v0.20 or higher" after running npm install -g composer-cli and getting this: 
/usr/bin/composer -> /usr/lib/node_modules/composer-cli/cli.js
+ composer-cli@0.20.0

**Comment by davidkel** [comment]
This is an environmental problem with your set up. With all shells whether a command can be found to be executed depends on whether the directory it exists in is on the PATH. If not then it won't find it. Also if the composer-cli has failed to install maybe due to npm install being run under sudo, but this is not a bug in composer or in the shell script. 

You need to ensure that composer cli is in a directory on your PATH.
